[10.0][ADD] l10n fi business code validate
OCA/l10n-finland pull request #10
Opened 2017-10-24 10:55 UTC by jarmokortetjarvi

Adds a business id for partners.
Split to two modules: one just adds the field and other adds validation and formatting.
This way the validation will be optional, and the module can be installed in environments with incorrectly formatted business ids

2017-10-24 12:50 UTC, mlaitinen requested changes
There are some minor changes I'd like to see

2017-10-24 12:50 UTC, mlaitinen commented on l10n_fi_business_code/data/res_partner_id_category.xml
> +<openerp>
This is Odoo 10, please use `<odoo>` and in cases of `<openerp><data noupdate="1">` use `<odoo noupdate="1">`

2017-10-24 12:50 UTC, mlaitinen commented on l10n_fi_business_code/views/res_partner.xml
> +	<data>
`<data>` is unnecessary. Also, please check the indentation of this file.

2017-10-24 12:50 UTC, mlaitinen commented on l10n_fi_business_code_validate/data/res_partner_id_category.xml
> +<openerp>
Please change to `<odoo>`

2017-10-24 12:50 UTC, mlaitinen commented on l10n_fi_business_code_validate/models/res_partner_id_number.py
> +class ResPartnerIdNumber(models.Model):
What's the purpose of this class?

2017-10-24 12:50 UTC, mlaitinen commented on l10n_fi_edicode/data/res_partner_operator_einvoice.xml
> +<openerp>
Please use `<odoo>` instead and check the indentation of this file.

2017-10-24 12:50 UTC, mlaitinen commented on l10n_fi_edicode/models/res_partner.py
> +from openerp import api, fields, models
`from odoo` ..

2017-10-24 12:50 UTC, mlaitinen commented on l10n_fi_edicode/models/res_partner_operator_einvoice.py
> +from openerp import api, fields, models
`from odoo` ..

2017-10-24 12:50 UTC, mlaitinen commented on l10n_fi_edicode/models/res_partner.py
> +        compute='get_einvoice_operator_identifier',
Couldn't this be a `related` field?

2017-10-24 12:50 UTC, mlaitinen commented on l10n_fi_edicode/view/res_partner.xml
> +<openerp>
Use `<odoo>`, drop `<data>` and check indentations.

2017-10-24 13:19 UTC, jarmokortetjarvi commented
Fixed the formatting issues and removed the edicode-module. It had been merged to a wrong branch

2018-01-14 17:43 UTC, mlaitinen requested changes
LGTM except the payment term module related stuff

2018-01-14 17:43 UTC, mlaitinen commented on l10n_fi_payment_terms/README.rst
> -**Please note that this module will remove the default payment terms!**
Why is `l10n_fi_payment_terms` in the same PR? You seem to have another PR #12 open for almost the same thing.

2018-03-20 09:35 UTC, mlaitinen commented
@jarmokortetjarvi Looks good, but there's still the EDI code module in the README which is yet to be merged. Also there seems to be a merge conflict in the README file.

2018-07-26 10:10 UTC, closed without merging

2018-07-26 10:56 UTC, jarmokortetjarvi commented
The commit history was a tangled mess between oca/l10n-finland and tawasta/l10n-finland
Closed this and created a new PR #15 that has only the relevant commits via git subtree. The contents should be pretty much identical

2018-07-27 06:07 UTC, aisopuro commented on l10n_fi_business_code/models/res_partner.py
> +        compute=lambda s: s._compute_identification(
Not sure if it's a big problem, but I'll add a note here anyway: using a lambda here means that anyone who wants to extend this model cannot directly extend the computation method of the field `business_id` in an Odoo-like fashion: they either have to do some pretty gnarly monkeypatching, or extend `_compute_identification` and trust or ensure that their changes only apply to the computation of this field. I think it would be a little better if we just go the normal route and define real computation methods and then refer to them by string in the field definition.

2018-07-27 06:07 UTC, aisopuro commented on l10n_fi_business_code_validate/models/res_partner_id_category.py
> +                       2]  # Number-space specific multipliers
Could the comment be above, so the multipliers could fit on a single line?

2018-07-27 06:07 UTC, aisopuro commented on l10n_fi_business_code_validate/models/res_partner_id_category.py
> +        for number in business_id_number[0:7]:
We could iterate over the `zip` instead:
```python
for number, multiplier in zip(business_id_number[0:7], multipliers):
    validation_multiplier += multiplier * int(number)
```
Then we don't need `number_index`