Add Finnish payment terms
OCA/l10n-finland pull request #4
Opened 2017-04-24 06:36 UTC by jarmokortetjarvi

Add common Finnish payment terms and helper fields for displaying them in correct order (sequence) and searching (code) without using error-prone fields 'name' or 'note'

2017-04-24 12:30 UTC, mlaitinen requested changes
Great job. I'd skip the removal of the original payment terms.

2017-04-24 12:30 UTC, mlaitinen commented on l10n_fi_payment_terms/data/payment_terms_finnish.xml
> +        <delete model="account.payment.term" id="account.account_payment_term_immediate"/>
A bit hazardous for non-fresh installations. I'd leave the original payment terms untouched.

2017-04-24 12:30 UTC, mlaitinen commented on l10n_fi_payment_terms/models/payment_term.py
> +    code = fields.Char('Unique code')
I'm not sure if these fields are necessary. Nevertheless I'm not opposed to keeping them.

2017-04-24 12:30 UTC, mlaitinen commented on l10n_fi_payment_terms/README.rst
> +
OCA should be a maintainer as well

2017-04-30 12:56 UTC, jarmokortetjarvi commented on l10n_fi_payment_terms/models/payment_term.py
> +    code = fields.Char('Unique code')
I think these aren't absolutely necessary, but they are useful as alphabetical ordering is confusing in this instance. They should, however, be introduces in another module than a localization one.

2017-05-04 12:26 UTC, dreispt requested changes

2017-05-04 12:26 UTC, dreispt commented on l10n_fi_payment_terms/models/__init__.py
> +import payment_term
`from . import payment_term`

2017-05-04 12:26 UTC, dreispt commented on l10n_fi_payment_terms/__init__.py
> +import models
Use relative import: `from . import models`

2017-05-04 13:41 UTC, dreispt commented on l10n_fi_payment_terms/models/payment_term.py
> +    # 8. Business methods
Remove unneeded comments.

2017-05-04 13:46 UTC, dreispt commented on l10n_fi_payment_terms/models/payment_term.py
> +    code = fields.Char('Unique code')
On one hand it is not strictly necessary, on another hand IMHO these "code" fields can be useful.
So no concern on having it here.

2017-05-05 07:20 UTC, dreispt commented on l10n_fi_payment_terms/models/payment_term.py
> +# 1. Standard library imports:
Please remove all these guideline comments

2017-05-05 13:09 UTC, dreispt approved these changes

2017-05-05 14:45 UTC, mlaitinen approved these changes

2017-05-05 17:11 UTC, merged